name = "backerboost/crowdfund_cardano"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken crowdfund_cardanos for project 'backerboost/crowdfund_cardano'"

[repository]
user = "backerboost"
project = "crowdfund_cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
